version: "3.8"

services:
  postgres:
    container_name: postgres-kapital
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: Kapitalbestand
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data

  expense-tracker:
    container_name: kapitalbestand 
    image: kapitalbestand
    restart: unless-stopped
    environment:
      DB_DBMS: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: Kapitalbestand
      DB_HOST: postgres
    ports:
      - 8080:8080
