services:
  postgres:
    container_name: postgres-kapital
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kapitalbestand
      POSTGRES_USER: kapitalist
      # POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD: password
      # POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data

  kapitalbestand:
    build: . 
    image: kapitalbestand
    restart: unless-stopped
    environment:
      DB_DBMS: postgres
      DB_DATABASE: kapitalbestand
      DB_USER: kapitalist
      # DB_USER_FILE: /run/secrets/postgres-user
      DB_PASSWORD: password
      # DB_PASSWORD_FILE: /run/secrets/postgres-password
      DB_HOST: postgres
    ports:
      - 8080:8080
