version: "3.8"

services:
  postgres:
    container_name: postgres-kapital
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: Expenses
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  expense-tracker:
    container_name: kapitalbestand 
    build: .
    restart: unless-stopped
    environment:
      DB_DBMS: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: kapital
      DB_HOST: postgres
    ports:
      - 8080:8080
