ALTER TABLE "Categories" ALTER COLUMN "UserId" SET NOT NULL;
ALTER TABLE "Shops" ALTER COLUMN "UserId" SET NOT NULL;
ALTER TABLE "OneoffTransactions" ALTER COLUMN "UserId" SET NOT NULL;
ALTER TABLE "MonthlyTransactions" ALTER COLUMN "UserId" SET NOT NULL;

ALTER TABLE "Transactions" ALTER COLUMN "CategoryId" SET NOT NULL;
