CREATE TABLE IF NOT EXISTS "Users" (
  "id" SERIAL,
  "username" VARCHAR(255) NOT NULL UNIQUE,
  "hash" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Categories" (
  "id" SERIAL,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "UserId" INTEGER REFERENCES "Users" ("id") ON DELETE NO ACTION ON UPDATE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Shops" (
  "id" SERIAL,
  "name" VARCHAR(255) NOT NULL UNIQUE,
  "UserId" INTEGER REFERENCES "Users" ("id") ON DELETE NO ACTION ON UPDATE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Transactions" (
  "id" SERIAL,
  "isExpense" BOOLEAN NOT NULL,
  "amount" INTEGER NOT NULL,
  "description" TEXT,
  "CategoryId" INTEGER REFERENCES "Categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "ShopId" INTEGER REFERENCES "Shops" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "OneoffTransactions" (
  "id" SERIAL,
  "date" DATE NOT NULL,
  "TransactionId" INTEGER REFERENCES "Transactions" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "UserId" INTEGER REFERENCES "Users" ("id") ON DELETE NO ACTION ON UPDATE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")  
);

CREATE TABLE IF NOT EXISTS "MonthlyTransactions" (
  "id" SERIAL,
  "monthFrom" DATE NOT NULL,
  "monthTo" DATE,
  "TransactionId" INTEGER REFERENCES "Transactions" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "UserId" INTEGER REFERENCES "Users" ("id") ON DELETE NO ACTION ON UPDATE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
