version: "3.8"

services:
  postgres:
    container_name: postgres-kapitalbestand-dev
    image: postgres
    environment:
      POSTGRES_DB: kapitalbestand
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data
